---
title: "Untitled"
output: github_document:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##load data
```{r}
data(acs)
table_list <- list()
```
## import library
```{r include=FALSE}
library(tidyverse)
require(moonBook)
library(huxtable)
library(flextable)
library(officer)
source("../02_scripts/some_function.R")
```

## Table list
### T01 baseline
```{r}
mytable(Dx~.,data=acs)
moonBook::mytable(sex ~ age+Dx,data = acs, method = 3)  %>% 
  mytable2df()  %>% 
  flextable()-> table_list$"T1"
moonBook::mytable(sex ~ age+Dx,data = acs) %>% summary()
```


### T02 multiple simple linear models
```{r}
fit.table <-
  lm_table(y_name = "Ozone", df = airquality)  %>%
  flextable()
```

### T03 multiple models
```{r}
data(diamonds, package = 'ggplot2')
lm1 <- lm(log(price) ~ carat, diamonds)
lm2 <- lm(log(price) ~ depth, diamonds)
lm3 <- lm(log(price) ~ carat + depth, diamonds)
huxreg(lm1, lm2, lm3) 
```

### T04 correlation table: condition formatting
```{r}
library(psych)
data(attitude)
att_corr <- corr.test(as.matrix(attitude))

as_hux(att_corr$r)                                                             %>%
      set_background_color(where(att_corr$p < 0.05), 'yellow')                 %>%
      set_background_color(where(att_corr$p < 0.01), 'orange')                 %>%
      set_background_color(where(row(att_corr$p) == col(att_corr$p)), 'white') %>%
      huxtable::add_rownames(colname = '')                                     %>%
      huxtable::add_colnames()                                                 %>%
      set_all_borders(1)                                                       %>%
      set_number_format(2)                                                     %>% 
      as_flextable()
```

###survival analysis

#### Odds Ratio
```{r}
require(survival)
data(colon)
out1=glm(status~sex+age+rx+obstruct+node4,data=colon)
out2=glm(status~rx+node4,data=colon)
ORplot(out1,type=2,show.CI=TRUE,xlab="This is xlab",main="Odds Ratio")
```



##Export to csv file : mycsv
```{r}
mycsv(out,file="test.csv")
mycsv(out1,fil="test1.csv")
```

##table list and word file 
 - is flextable objector?
 - 
```{r}
table_list
dir.create("table")
```


## export to word
###single docx file👍
```{r}
read_docx() %>% 
  body_add_par("A title", style = "heading 1") %>%
  body_add_par("Hello world!", style = "Normal") %>%
  body_add_par("centered text", style = "centered")
  print(target="table/table.docx")
black_docx <- function(table){
  read_docx("table/table.docx") %>% 
    body_add_break() %>% 
    body_add_flextable(flextable(table)) %>% 
    print(target = "table/table.docx")
}
map(table_list, black_docx)
```

###multiple docx file 👍
```{r}
labels <- names(table_list)
zero_docx <- function(table,labels){
  read_docx() %>% 
  body_add_flextable(flextable(as.data.frame(table))) %>% 
  print(target = str_c("table/",labels,".docx"))
}
map2(table_list, labels, zero_docx)
```

```{r}
read_docx() %>% 
  body_add_flextable()
```

